[package]
name = "pyth2wormhole"
version = "0.1.0"
description = "Pyth to Wormhole solana on-chain integration"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "pyth2wormhole"

[features]
client = ["solitaire/client", "solitaire-client", "no-entrypoint"]
no-entrypoint = []

[dependencies]
bridge = {path = "../../bridge/program"}
solitaire = { path = "../../solitaire/program" }
solitaire-client = { path = "../../solitaire/client", optional = true }
pyth-client = {git = "https://github.com/drozdziak1/pyth-client-rs", branch = "v2-clone-and-debug"}
rocksalt = { path = "../../solitaire/rocksalt" }
solana-program = "=1.7.0"
borsh = "0.8.1"
